openapi: 3.0.0
info:
  title: GraphLans API
  description: API for GraphLabs
  version: 1.0.0
servers:
  - url: /api/v1
    description: Main API server
tags:
  - name: user
    description: User operations
  - name: teacher
    description: Teacher operations
paths:
  /ping:
    get:
      summary: Ping service
      responses:
        '200':
          description: Successful ping response
          content:
            text/plain:
              example: pong

  /api/v1/user/auth_user:
    post:
      tags: [user]
      summary: Authenticate user
      responses:
        '200':
          description: Successful authentication
        '400':
          description: Bad request
        '500':
          description: Internal server error

  /api/v1/teacher/create_student:
    post:
      tags: [teacher]
      summary: Create new student
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateStudentDTOIn'
      responses:
        '200':
          description: Student created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateStudentDTOOut'
        '400':
          description: Bad request
        '500':
          description: Internal server error

  /api/v1/teacher/modules:
    get:
      tags: [teacher]
      summary: Get all modules
      responses:
        '200':
          description: List of modules
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetModulesDTOOut'
        '500':
          description: Internal server error

  /api/v1/teacher/create_lab:
    post:
      tags: [teacher]
      summary: Create new lab
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateLabDTOIn'
      responses:
        '200':
          description: Lab created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateLabDTOOut'
        '400':
          description: Bad request
        '500':
          description: Internal server error

  /api/v1/teacher/lab_info:
    post:
      tags: [teacher]
      summary: Get lab information
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetLabInfoDTOIn'
      responses:
        '200':
          description: Lab information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetLabInfoDTOOut'
        '400':
          description: Bad request
        '500':
          description: Internal server error

  /api/v1/teacher/remove_user_lab:
    post:
      tags: [teacher]
      summary: Remove user lab assignment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RemoveUserLabDTOIn'
      responses:
        '200':
          description: User lab removed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RemoveUserLabDTOOut'
        '400':
          description: Bad request
        '500':
          description: Internal server error

  /api/v1/teacher/update_lab_info:
    patch:
      tags: [teacher]
      summary: Update lab information
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateLabInfoDTOIn'
      responses:
        '200':
          description: Lab updated successfully
        '400':
          description: Bad request
        '500':
          description: Internal server error

  /api/v1/teacher/assigne_lab:
    post:
      tags: [teacher]
      summary: Assign lab to student
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AssignLabDTOIn'
      responses:
        '200':
          description: Lab assigned successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AssignLabDTOOut'
        '400':
          description: Bad request
        '500':
          description: Internal server error

  /api/v1/teacher/assigne_lab_group:
    post:
      tags: [teacher]
      summary: Assign lab to group
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AssignLabGroupDTOIn'
      responses:
        '200':
          description: Lab assigned to group successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AssignLabGroupDTOOut'
        '400':
          description: Bad request
        '500':
          description: Internal server error

  /api/v1/teacher/module_lab:
    post:
      tags: [teacher]
      summary: Add module to lab
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddModuleLabDTOIn'
      responses:
        '200':
          description: Module added to lab successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AddModuleLabDTOOut'
        '400':
          description: Bad request
        '500':
          description: Internal server error

  /api/v1/teacher/remove_module_lab:
    post:
      tags: [teacher]
      summary: Remove module from lab
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RemoveModuleLabDTOIn'
      responses:
        '200':
          description: Module removed from lab successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RemoveModuleLabDTOOut'
        '400':
          description: Bad request
        '500':
          description: Internal server error

  /api/v1/teacher/not_assigned_labs:
    post:
      tags: [teacher]
      summary: Get non-assigned labs
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetNonAssignedLabsDTOIn'
      responses:
        '200':
          description: List of non-assigned labs
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetNonAssignedLabsDTOOut'
        '400':
          description: Bad request
        '500':
          description: Internal server error

  /api/v1/teacher/assigned_labs:
    post:
      tags: [teacher]
      summary: Get assigned labs
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetAssignedLabsDTOIn'
      responses:
        '200':
          description: List of assigned labs
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAssignedLabsDTOOut'
        '400':
          description: Bad request
        '500':
          description: Internal server error

  /api/v1/teacher/lab_modules:
    post:
      tags: [teacher]
      summary: Get lab modules
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetLabModulesDTOIn'
      responses:
        '200':
          description: List of lab modules
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetLabModulesDTOOut'
        '400':
          description: Bad request
        '500':
          description: Internal server error

components:
  schemas:
    CreateStudentDTOIn:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        fatherName:
          type: string
        groupId:
          type: integer
          format: int64

    CreateStudentDTOOut:
      type: object
      properties:
        userId:
          type: integer
          format: int64

    GetModulesDTOOut:
      type: object
      properties:
        modules:
          type: array
          items:
            $ref: '#/components/schemas/Module'

    CreateLabDTOIn:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        duration:
          type: integer
          format: int64
        registrationDate:
          type: string
          format: date-time
        teacherId:
          type: integer
          format: int64

    CreateLabDTOOut:
      type: object
      properties:
        labId:
          type: integer
          format: int64

    GetLabInfoDTOIn:
      type: object
      properties:
        labId:
          type: integer
          format: int64

    GetLabInfoDTOOut:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        duration:
          type: integer
          format: int64
        registrationDate:
          type: string
          format: date-time
        teacherId:
          type: integer
          format: int64
        teacherFio:
          type: string

    RemoveUserLabDTOIn:
      type: object
      properties:
        userId:
          type: integer
          format: int64
        labId:
          type: integer
          format: int64

    RemoveUserLabDTOOut:
      type: object
      properties:
        userLabId:
          type: integer
          format: int64

    UpdateLabInfoDTOIn:
      type: object
      properties:
        labId:
          type: integer
          format: int64
        labName:
          type: string
        description:
          type: string
        duration:
          type: integer
          format: int64

    AssignLabDTOIn:
      type: object
      properties:
        userId:
          type: integer
          format: int64
        labId:
          type: integer
          format: int64
        assignmentDate:
          type: string
          format: date-time
        startTime:
          type: string
          format: date-time
        deadline:
          type: string
          format: date-time

    AssignLabDTOOut:
      type: object
      properties:
        userLabId:
          type: integer
          format: int64

    AssignLabGroupDTOIn:
      type: object
      properties:
        labId:
          type: integer
          format: int64
        assignmentDate:
          type: string
          format: date-time
        startTime:
          type: string
          format: date-time
        deadline:
          type: string
          format: date-time
        groupId:
          type: integer
          format: int64

    AssignLabGroupDTOOut:
      type: object
      properties:
        labId:
          type: integer
          format: int64

    AddModuleLabDTOIn:
      type: object
      properties:
        labId:
          type: integer
          format: int64
        moduleId:
          type: integer
          format: int64
        weight:
          type: string
          format: decimal

    AddModuleLabDTOOut:
      type: object
      properties:
        moduleLabId:
          type: integer
          format: int64

    RemoveModuleLabDTOIn:
      type: object
      properties:
        labId:
          type: integer
          format: int64
        moduleId:
          type: integer
          format: int64

    RemoveModuleLabDTOOut:
      type: object
      properties:
        moduleLabId:
          type: integer
          format: int64

    GetNonAssignedLabsDTOIn:
      type: object
      properties:
        page:
          type: integer
          format: int64

    GetNonAssignedLabsDTOOut:
      type: object
      properties:
        labs:
          type: array
          items:
            $ref: '#/components/schemas/Lab'

    GetAssignedLabsDTOIn:
      type: object
      properties:
        page:
          type: integer
          format: int64

    GetAssignedLabsDTOOut:
      type: object
      properties:
        labs:
          type: array
          items:
            $ref: '#/components/schemas/UserLabWithInfo'

    GetLabModulesDTOIn:
      type: object
      properties:
        labId:
          type: integer
          format: int64

    GetLabModulesDTOOut:
      type: object
      properties:
        labId:
          type: integer
          format: int64
        modules:
          type: array
          items:
            $ref: '#/components/schemas/ModulesInLab'

    Lab:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        description:
          type: string
        duration:
          type: string
        registrationDate:
          type: string
          format: date-time
        teacherId:
          type: integer
          format: int64
        teacherFio:
          type: string

    Module:
      type: object
      properties:
        moduleId:
          type: integer
          format: int64
        moduleType:
          type: string
        description:
          type: string

    UserLabWithInfo:
      type: object
      properties:
        userLabId:
          type: integer
          format: int64
        labId:
          type: integer
          format: int64
        labName:
          type: string

    ModulesInLab:
      type: object
      properties:
        moduleLabId:
          type: integer
          format: int64
        labId:
          type: integer
          format: int64
        moduleId:
          type: integer
          format: int64
        moduleType:
          type: string